### ISSUE TITLE
Python package ImportError

### ISSUE THREAD

**Issue by nacharov** [covid19kg/covid19kg#3]
I tried to install covid19kg package (I cloned repo and run 'pip install -e .'). Unfortunately, covid19kg command returns ImportError

How this issue can be solved? 

covid19kg nacharov$ covid19kg
Traceback (most recent call last):
  File "/Users/nacharov/anaconda3/bin/covid19kg", line 11, in <module>
    load_entry_point('covid19kg', 'console_scripts', 'covid19kg')()
  File "/Users/nacharov/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/nacharov/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/Users/nacharov/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/Users/nacharov/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Volumes/Data/dev/CoVid-19 analysis/covid19-kg/covid19kg/covid19kg/__init__.py", line 7, in <module>
    from bel_repository import BELMetadata, BELRepository
  File "/Users/nacharov/anaconda3/lib/python3.6/site-packages/bel_repository/__init__.py", line 6, in <module>
    from .repository import BELRepository  # noqa: F401
  File "/Users/nacharov/anaconda3/lib/python3.6/site-packages/bel_repository/repository.py", line 20, in <module>
    from pybel.cli import connection_option, host_option, password_option, user_option
ImportError: cannot import name 'password_option'

**Comment by ddomingof** [comment]
Hi @nacharov, sorry for the delay. I somehow missed the issue notification. I assume the problem has been fixed now.
